{
    'name': 'Rakib Development Tutorials',
    'version': '13.0.2.1.0',
    'summary': """Odoo 13 Development Tutorials.""",
    'sequence': '-100',
    'description': """Odoo 13 Development Tutorials.""",
    'category': 'Tutorials',
    'author': 'Fahim Hasan',
    'maintainer': 'Fahim Hasan',
    'license': 'AGPL-3',
    'depends': [

    ],
    'data': [
        'security/ir.model.access.csv',
        'data/patient_sequence.xml',
        'data/appointment_sequence.xml',
        'data/doctor_sequence.xml',
        'views/menu_view.xml',
        'views/patient_view.xml',
        'views/male_patient_view.xml',
        'views/female_patient_view.xml',
        'views/kids_view.xml',
        'views/appointment.xml',
        'views/doctor_view.xml',
        'views/male_doctors.xml',
        'views/female_doctor.xml',
    ],
    'demo': [],
    'qweb': [],
    'installable': True,
    'application': True,
    'auto_install': False,
}
